steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kamal-dashboard', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'kamal-dashboard',
           '--image', 'gcr.io/$PROJECT_ID/kamal-dashboard',
           '--region', 'us-central1',  # Change only if you are using another region
           '--platform', 'managed',
           '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/kamal-dashboard'
