steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'asia-south1-docker.pkg.dev/kamal---dashboard/cloud-run-source-deploy/kamal-trading-dashboard'
      - '--builder=gcr.io/buildpacks/builder'
    env:
      - 'GOOGLE_ENTRYPOINT=streamlit run app.py'

images:
  - 'asia-south1-docker.pkg.dev/kamal---dashboard/cloud-run-source-deploy/kamal-trading-dashboard'
