steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kamal-dashboard', '.']
  
  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kamal-dashboard']
  
  # Step 3: Deploy to Cloud Run with proper configuration
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'kamal-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kamal-dashboard'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      #- '--port'
      #- '8501'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      #- '--set-env-vars'
      #- 'PORT=8501'

# Logging configuration to prevent the original error
options:
  logging: CLOUD_LOGGING_ONLY
  
# Machine type for better performance
 # machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s'

