# Add this to indian_stock_logic.py to replace get_expanded_nse_universe()

def get_expanded_nse_universe():
    """Complete NSE 500 universe with all sectors"""
    
    # You can either:
    # Option 1: Fetch NSE 500 list dynamically
    try:
        nse500_df = pd.read_csv("https://archives.nseindia.com/content/indices/ind_nifty500list.csv")
        symbols = [symbol + ".NS" for symbol in nse500_df['Symbol'].tolist()]
        return symbols
    except:
        # Option 2: Fallback to expanded static list
        pass
    
    # Extended static list covering major NSE stocks across all sectors
    return [
        # NIFTY 50 - Large Cap Blue Chips
        "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
        "KOTAKBANK.NS", "SBIN.NS", "BHARTIARTL.NS", "ASIANPAINT.NS", "ITC.NS",
        "AXISBANK.NS", "LT.NS", "SUNPHARMA.NS", "TITAN.NS", "WIPRO.NS",
        "MARUTI.NS", "BAJFINANCE.NS", "TATASTEEL.NS", "ONGC.NS", "COALINDIA.NS",
        "HINDUNILVR.NS", "M&M.NS", "HCLTECH.NS", "NTPC.NS", "ADANIENT.NS",
        "POWERGRID.NS", "ULTRACEMCO.NS", "TATAMOTORS.NS", "NESTLEIND.NS", "BAJAJ-AUTO.NS",
        "GRASIM.NS", "JSWSTEEL.NS", "TECHM.NS", "INDUSINDBK.NS", "DRREDDY.NS",
        "CIPLA.NS", "HEROMOTOCO.NS", "SBILIFE.NS", "DIVISLAB.NS", "BRITANNIA.NS",
        "BPCL.NS", "EICHERMOT.NS", "SHREECEM.NS", "BAJAJFINSV.NS", "HINDALCO.NS",
        "ADANIPORTS.NS", "TATACONSUM.NS", "APOLLOHOSP.NS", "HDFCLIFE.NS", "DABUR.NS",
        
        # NIFTY NEXT 50
        "SIEMENS.NS", "ADANITRANS.NS", "ADANIGREEN.NS", "DLF.NS", "GODREJCP.NS",
        "AMBUJACEM.NS", "INDIGO.NS", "INDUSTOWER.NS", "TORNTPHARM.NS", "MCDOWELL-N.NS",
        "ICICIGI.NS", "HAVELLS.NS", "GAIL.NS", "VEDL.NS", "ICICIPRULI.NS",
        "PNB.NS", "BANKBARODA.NS", "BOSCHLTD.NS", "MARICO.NS", "TATAPOWER.NS",
        "COLPAL.NS", "PIDILITIND.NS", "JINDALSTEL.NS", "LTI.NS", "BERGEPAINT.NS",
        "SRF.NS", "MOTHERSUMI.NS", "AUROPHARMA.NS", "SAIL.NS", "ADANIPOWER.NS",
        "IOC.NS", "MUTHOOTFIN.NS", "CHOLAFIN.NS", "UBL.NS", "ZYDUSLIFE.NS",
        "JUBLFOOD.NS", "BIOCON.NS", "NAUKRI.NS", "PEL.NS", "ABB.NS",
        "TORNTPOWER.NS", "ALKEM.NS", "BANDHANBNK.NS", "IRCTC.NS", "IGL.NS",
        "YESBANK.NS", "LICHSGFIN.NS", "NMDC.NS", "SRTRANSFIN.NS", "CANBK.NS",
        
        # MIDCAP 150
        "VOLTAS.NS", "FEDERALBNK.NS", "ESCORTS.NS", "BATAINDIA.NS", "BALKRISIND.NS",
        "TVSMOTOR.NS", "PAGEIND.NS", "ASTRAL.NS", "MRF.NS", "3MINDIA.NS",
        "COFORGE.NS", "PERSISTENT.NS", "LTTS.NS", "MINDTREE.NS", "MPHASIS.NS",
        "APOLLOTYRE.NS", "CUMMINSIND.NS", "CROMPTON.NS", "HAL.NS", "BEL.NS",
        "CONCOR.NS", "BHARATFORG.NS", "IDFCFIRSTB.NS", "MANAPPURAM.NS", "L&TFH.NS",
        "M&MFIN.NS", "RECLTD.NS", "PFC.NS", "GMRINFRA.NS", "NATIONALUM.NS",
        "AIAENG.NS", "RAMCOCEM.NS", "DALBHARAT.NS", "ABCAPITAL.NS", "AUBANK.NS",
        "TRENT.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PRESTIGE.NS", "PHOENIXLTD.NS",
        "INDHOTEL.NS", "LALPATHLAB.NS", "METROPOLIS.NS", "LAURUSLABS.NS", "GLAND.NS",
        "NATCOPHARM.NS", "DEEPAKNTR.NS", "NAVINFLUOR.NS", "AARTIIND.NS", "CHAMBLFERT.NS",
        "COROMANDEL.NS", "UPL.NS", "PIIND.NS", "RELAXO.NS", "DIXON.NS",
        "POLYCAB.NS", "KEI.NS", "HAVELLS.NS", "CGPOWER.NS", "POWERINDIA.NS",
        "SCHAEFFLER.NS", "TIMKEN.NS", "SKF.NS", "HONAUT.NS", "THERMAX.NS",
        "CESC.NS", "NIACL.NS", "STARHEALTH.NS", "HDFCAMC.NS", "NIPPONLIFE.NS",
        "MAXHEALTH.NS", "FORTIS.NS", "SYNGENE.NS", "THYROCARE.NS", "TEAMLEASE.NS",
        "QUESS.NS", "BLUEDART.NS", "MAHLOG.NS", "VBL.NS", "ZOMATO.NS",
        "NYKAA.NS", "PAYTM.NS", "POLICYBZR.NS", "CARTRADE.NS", "CLEAN.NS",
        
        # SMALLCAP 250 - Select High Quality
        "CREDITACC.NS", "ECLERX.NS", "FINEORG.NS", "HAPPSTMNDS.NS", "HATHWAY.NS",
        "HEIDELBERG.NS", "HONAUT.NS", "IFBIND.NS", "INGERRAND.NS", "JBCHEPHARM.NS",
        "JKLAKSHMI.NS", "JMFINANCIL.NS", "JSWENERGY.NS", "JUBILANT.NS", "JUSTDIAL.NS",
        "KAJARIACER.NS", "KALPATPOWR.NS", "KANSAINER.NS", "KARURVYSYA.NS", "KEC.NS",
        "KIRLOSENG.NS", "KOLTEPATIL.NS", "KRBL.NS", "KSCL.NS", "LAOPALA.NS",
        "LEMONTREE.NS", "LINDEINDIA.NS", "LUXIND.NS", "MAHABANK.NS", "MAHINDCIE.NS",
        "MAHLIFE.NS", "MAHSCOOTER.NS", "MAHSEAMLES.NS", "MANINFRA.NS", "MASFIN.NS",
        "MCX.NS", "MINDACORP.NS", "MOIL.NS", "MOTILALOFS.NS", "MPHASIS.NS",
        "MRPL.NS", "NATCOPHARM.NS", "NAVNETEDUL.NS", "NBCC.NS", "NCC.NS",
        "NESCO.NS", "NETWORK18.NS", "NH.NS", "NHPC.NS", "NIITTECH.NS",
        "NLCINDIA.NS", "NOCIL.NS", "OFSS.NS", "OIL.NS", "OMAXE.NS",
        "ORIENTCEM.NS", "ORIENTELEC.NS", "ORIENTREF.NS", "PAGEIND.NS", "PARAGMILK.NS",
        "PCJEWELLER.NS", "PERSISTENT.NS", "PFIZER.NS", "PHILIPCARB.NS", "PHOENIXLTD.NS",
        "POLYMED.NS", "POWERMECH.NS", "PPAP.NS", "PRAJIND.NS", "PRINCEPIPE.NS",
        "PRSMJOHNSN.NS", "QUESS.NS", "RADICO.NS", "RAIN.NS", "RAJESHEXPO.NS",
        "RALLIS.NS", "RKFORGE.NS", "REDINGTON.NS", "RELAXO.NS", "RELIGARE.NS",
        "RENUKA.NS", "RESPONIND.NS", "RITES.NS", "ROSSARI.NS", "ROUTE.NS",
        "RPGLIFE.NS", "RPOWER.NS", "RUCHI.NS", "RVNL.NS", "SAFARI.NS",
        "SAGARCEM.NS", "SANOFI.NS", "SAPPHIRE.NS", "SASKEN.NS", "SBICARD.NS",
        "SCHNEIDER.NS", "SCI.NS", "SEQUENT.NS", "SHARDACROP.NS", "SHILPAMED.NS",
        "SHK.NS", "SHOPERSTOP.NS", "SHREECEM.NS", "SHRIRAMCIT.NS", "SJVN.NS",
        "SKFINDIA.NS", "SOBHA.NS", "SOLARA.NS", "SOLARINDS.NS", "SONATSOFTW.NS",
        "SOUTHBANK.NS", "SPANDANA.NS", "SPARC.NS", "SPICEJET.NS", "STARCEMENT.NS",
        "STLTECH.NS", "SUDARSCHEM.NS", "SUNDARMFIN.NS", "SUNDRMFAST.NS", "SUNTECK.NS",
        "SUNTV.NS", "SUPPETRO.NS", "SUPREMEIND.NS", "SUVENPHAR.NS", "SUZLON.NS",
        "SWANENERGY.NS", "SWSOLAR.NS", "SYMPHONY.NS", "SYNGENE.NS", "TAKE.NS",
        "TASTYBITE.NS", "TATACHEM.NS", "TATACOFFEE.NS", "TATACOMM.NS", "TATAELXSI.NS",
        "TATAINVEST.NS", "TATAMETALI.NS", "TCIEXP.NS", "TCNSBRANDS.NS", "TEAMLEASE.NS",
        "TECHNO.NS", "TECHNOE.NS", "THYROCARE.NS", "TIDEWATER.NS", "TIINDIA.NS",
        "TIMKEN.NS", "TINPLATE.NS", "TIPSINDLTD.NS", "TIRUMALCHM.NS", "TNPETRO.NS",
        "TNPL.NS", "TRENT.NS", "TRIDENT.NS", "TRITURBINE.NS", "TRIVENI.NS",
        "TTKPRESTIG.NS", "TV18BRDCST.NS", "TVSELECT.NS", "TVSSRICHAK.NS", "TVTODAY.NS",
        "UCOBANK.NS", "UFLEX.NS", "UJJIVAN.NS", "UJJIVANSFB.NS", "ULTRACEMCO.NS",
        "UNICHEMLAB.NS", "UNIONBANK.NS", "UNITECH.NS", "UNITEDBNK.NS", "UNITY.NS",
        "UNIVCABLES.NS", "UPERGANGES.NS", "USHAMART.NS", "UTIAMC.NS", "VAIBHAVGBL.NS",
        "VAKRANGEE.NS", "VALIANTORG.NS", "VARROC.NS", "VBL.NS", "VEDL.NS",
        "VENKEYS.NS", "VENUSREM.NS", "VESUVIUS.NS", "VGUARD.NS", "VINATIORGA.NS",
        "VIPIND.NS", "VMART.NS", "VOLTAMP.NS", "VOLTAS.NS", "VRLLOG.NS",
        "VSTIND.NS", "VTL.NS", "WABAG.NS", "WABCOINDIA.NS", "WALCHANNAG.NS",
        "WELCORP.NS", "WELSPUNIND.NS", "WESTLIFE.NS", "WHIRLPOOL.NS", "WOCKPHARMA.NS",
        "WONDERLA.NS", "WSTCSTPAPR.NS", "XPROINDIA.NS", "YESBANK.NS", "ZEEL.NS",
        "ZENSARTECH.NS", "ZENTEC.NS", "ZFCVINDIA.NS", "ZODIACLOTH.NS", "ZORINFRA.NS",
        "ZYDUSWELL.NS"
    ]
